name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # No need to change this, it will use Node.js 20 automatically

      - name: Install TruffleHog
        run: |
          npm install -g trufflehog

      - name: Run TruffleHog
        run: |
          trufflehog filesystem --directory . --json > trufflehog_report.json

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog_report.json
